dist: trusty
sudo: false
language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# Java 10 "Oracle JDK"
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

install: ./gradlew --version

script: 
- ./gradlew server:test -Dbuild.snapshot=false
- ./gradlew assemble -Dbuild.snapshot=false

before_deploy:
  - export TARBALL=$(ls distribution/tar/build/distributions/elassandra-*.tar.gz)
  - export ZIPBALL=$(ls distribution/zip/build/distributions/elassandra-*.zip)
  - export DEBPKG=$(ls distribution/deb/build/distributions/elassandra-*.deb)
  - export RPMPKG=$(ls distribution/rpm/build/distributions/elassandra-*.rpm)

deploy:
  - provider: releases
    overwrite: true
    draft: false
    api_key:
      secure: "MFhecFMYXJRTZYYTY0zrvQyDoTUXtaODNuF/Im7pFZDbC7aWgo5s8HFmyzNpJADKwydO1RLFPpEhJGTJ/FbuTDvshc/PirzVbrVr4jK0hnNCFaYEBqOypJzoR1j5bdivmMWxaHVvKEfAr+iNs9fwEVeb3uS+JrsZspImBkDbbeuOq0SKyxl1CrE1KF3aZJWOv50zKJaGyre9dKUq9JL8Js2dNKpebYhP8tjhD7iShD344I00br9qu3ThZ3rG6LTv4c3llI0ZRhWb644iNFtz9CoKQXK30ATjh1avT1wZr6Ci+62kYAePBToagbHd5xs8S78hFkUcm7Z0/8XX8m5KJNyJl+MSh0F/vkEpBJaLSqwUPcgbEB5wqYvWDTWADY9rQ80Mv6I97kmxpYPGpRLONBxjDby2fUVGnyr+7tWhAmAXOomtMXMl6LOLHCp0gNFMO2Twp77vTRz8e38B2dJ5vg155bGNHM7kBwP3EuiKiKFwA+RUpukVLQon7foGvikEsB1HLrNoOg44QEzrcEL6UP9tHyEFWWfwSnD3q7ybQ7bjzFC4N9F1t/NpYI2icR8X/3dRrj4GjWMCMWK75HZWjycrfd0nNLdhKyGAw2rlTmgq6Sypm3g80aq3LvGJ+Pnb7s6B2IAzNgOyhT8TKlIILZ3wQlYMrVBaVaMTmRItHWY="
    file:
      - "$TARBALL"
      - "$ZIPBALL"
      - "$RPMPKG"
      - "$DEBPKG"
    skip_cleanup: true
    on:
      tags: true
      repo: strapdata/elassandra

  - provider: releases
    overwrite: true
    draft: false
    api_key:
      secure: "IGw9pr6twtu6JxN2qRbCvDtdIQuJvFxdjXCJrr1YsB8K1kFJlbUcJcQ4BHbisL2oRQFJyWDcx7wiDPL6/6ViiJfnNtPUAVQLDgxQtQXA+TNGK8UI7q06bDsPusaodo8iwkton5I6Q2AHtwxaZ7jgkfxpI8YMyjo4DvzGvbNuAC4WNImEqifcC+nMxIbREOo85Q6ZHFoQiVA7SvPUYta1k3s8r2tC84UL8s6tO+T+iiO70Tc4dVAfIsA2vNlea8aOlK+zPITFIPxG7xdlzkkP3KpLSR4yZF67wP9i6j4LNYfa43WLHSDmy3OPw8AC3ceeex8xL+lP7F/eASOxzwnXjXMOd/TAW4AsYeqnGwaqtBVfFFwpqueowKqE+5s9j0Kll4PFMsYSKz0rV1JGWE/SAHzr1NDtNHdFUytJAnzqScdQsWUpNAePQGlugYy1JtAiuGSMVt7na31mdGZzGlzcjvZEe+x6NJTI6dMe5CTEsdXpsT8RBFH6od1rXi9wOqcyTAofED4ZooGwmMznGKxdW0hHsSjAh1DGk93GKM5KmJjPqldc6g6oYq0NZkrtPIvEsQCenu0dByxQH6pAJt2CmA2WCnIVDg5Qoy8qTCs7BDBkKSCuq/ICEHU3vSD66xLzAMfldZPPtsgyN217Ho6fVYkTsY2Xl5kIVGcxN56D/zk="
    file:
      - "$TARBALL"
      - "$ZIPBALL"
      - "$RPMPKG"
      - "$DEBPKG"
    skip_cleanup: true
    on:
      tags: true
      repo: strapdata/elassandra6-rc
